apiVersion: v2
name: kcert
description: Deploys KCert for issuing Let's Encrypt certificates 
version: 1.0.4
appVersion: 1.2.0
maintainers:
- name: Nabeel Sulieman
  url: https://nabeel.dev
keywords:
- kubernetes
- letsencrypt
- ssl
sources:
 - https://github.com/nabsul/kcert
